version: "3"
services:
  redis:
    image: redis:4
    ports:
      - 6379:6379
    volumes:
      - /root/redis/conf:/usr/local/etc/redis
      - /root/redis/data:/data/redis
    command:
      redis-server
